### ISSUE TITLE
Remove usage of `database.writeOptions` as it is now deprecated/error prone

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-resource-restriction#19]
With the mongo 3.x driver, `database.writeOptions` are set in the client via bedrock-mongodb and do not need to be applied on every mongo collection call. We should not be passing them into every call as this creates a maintenance headache and is error prone (a fix in the core options will not propagate to any call that is sending in the options itself rather than using the defaults as it should). Note that we need to be careful when applying this change to make sure it does, in fact, use the proper defaults -- and especially careful when sending in options such as `upsert` -- so that only `upsert` is changed and we still get to use the defaults that we set on the client itself.

**Comment by JSAssassin** [comment]
Closing. Addressed by #51
