### ISSUE TITLE
Fix data type on `acquisition.expires` field

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-resource-restriction#27]
https://github.com/digitalbazaar/bedrock-resource-restriction/blob/cf576a5baa20929c8f6819e16adc5240f43576e8/lib/ResourceTokenizer.js#L404

This field works in conjunction with a TTL index
https://docs.mongodb.com/manual/tutorial/expire-data/

For this to work, the `acquisition.expires` needs to be a Date, it is currently being recorded as seconds since the epoch.

**Comment by dlongley** [comment]
We need to wrap `expires` in a date here (watch out for `undefined` case -- determine if that can happen and if so, handle it): https://github.com/digitalbazaar/bedrock-resource-restriction/blob/cf576a5baa20929c8f6819e16adc5240f43576e8/lib/resources.js#L342

And we need to transform back before this line here: https://github.com/digitalbazaar/bedrock-resource-restriction/blob/cf576a5baa20929c8f6819e16adc5240f43576e8/lib/resources.js#L318

**Comment by aljones15** [comment]
Relevant to testing:

> The background task that removes expired documents runs every 60 seconds. As a result, documents may remain in a collection during the period between the expiration of the document and the running of the background task.
> 
> Because the duration of the removal operation depends on the workload of your mongod instance, expired data may exist for some time beyond the 60 second period between runs of the background task.

**Comment by dlongley** [comment]
@mandyvenables -- I'm leaving this open for a unit test (that runs only on CI) that ensures expires is working.

**Comment by dlongley** [comment]
Addressed by #31.
